name: Build Agent EXE

on:
  workflow_dispatch:
  push:
    paths:
      - 'WindowsAgentAIOInstall.ps1'
      - '.github/workflows/build-agent.yml'

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v4

      - name: Enable TLS1.2 + ExecutionPolicy Bypass
        shell: pwsh
        run: |
          [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
          Set-ExecutionPolicy Bypass -Scope Process -Force

      # Usamos o ps2exe.ps1 "raw" para evitar incompatibilidade de parâmetros
      - name: Download ps2exe.ps1 (raw)
        shell: pwsh
        run: |
          Invoke-WebRequest https://raw.githubusercontent.com/MScholtes/PS2EXE/master/ps2exe.ps1 -OutFile ps2exe.ps1

      - name: Compile EXE
        shell: pwsh
        run: |
          $src = Resolve-Path .\WindowsAgentAIOInstall.ps1
          $out = Join-Path $PWD 'SafeCompliance-RustDesk-Agent.exe'
          powershell -NoProfile -ExecutionPolicy Bypass -File .\ps2exe.ps1 `
            "$src" "$out" -noconsole -requireAdmin `
            -title 'SafeCompliance RustDesk Agent' `
            -company 'SafeCompliance' `
            -product 'RustDesk Agent Installer' `
            -fileversion '1.0.0.0'
          if (-not (Test-Path $out)) { throw "EXE não foi gerado." }
          (Get-Item $out).FullName

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: SafeCompliance-RustDesk-Agent.exe
          path: SafeCompliance-RustDesk-Agent.exe

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.run_number }}
          name: "Agent build ${{ github.run_number }}"
          files: SafeCompliance-RustDesk-Agent.exe
