name: Build Agent EXE

on:
  workflow_dispatch:
  push:
    paths:
      - 'WindowsAgentAIOInstall.ps1'

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v4

      - name: Enable TLS1.2 + ExecutionPolicy Bypass
        shell: powershell
        run: |
          [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
          Set-ExecutionPolicy Bypass -Scope Process -Force

      - name: Install ps2exe module (PowerShell Gallery)
        shell: powershell
        run: |
          Install-PackageProvider -Name NuGet -Force -Scope CurrentUser
          Set-PSRepository -Name PSGallery -InstallationPolicy Trusted
          Install-Module -Name ps2exe -Scope CurrentUser -Force
          Import-Module ps2exe

      - name: Compile EXE
        shell: powershell
        run: |
          $src = Resolve-Path .\WindowsAgentAIOInstall.ps1
          $out = Join-Path $PWD 'SafeCompliance-RustDesk-Agent.exe'
          Import-Module ps2exe
          Invoke-ps2exe -inputFile $src -outputFile $out -noConsole -requireAdmin `
            -title   'SafeCompliance RustDesk Agent' `
            -company 'SafeCompliance' `
            -product 'RustDesk Agent Installer'

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: SafeCompliance-RustDesk-Agent.exe
          path: SafeCompliance-RustDesk-Agent.exe

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.run_number }}
          name: "Agent build ${{ github.run_number }}"
          files: SafeCompliance-RustDesk-Agent.exe
